// Configuración de campos específicos por categoría
// Basado en los campos de compraensanjuan.com + mejoras

export type FieldType = "select" | "number" | "text" | "checkbox" | "radio";

export interface CategoryField {
  key: string;
  label: string;
  type: FieldType;
  options?: { value: string; label: string }[];
  placeholder?: string;
  required?: boolean;
  unit?: string; // km, m², etc.
  hint?: string;
}

export interface CategoryConfig {
  id: number;
  name: string;
  slug: string;
  icon: string;
  fields: CategoryField[];
  subcats?: { value: string; label: string }[];
}

const ZONAS_SJ = [
  { value: "capital", label: "Capital" },
  { value: "rivadavia", label: "Rivadavia" },
  { value: "rawson", label: "Rawson" },
  { value: "santa-lucia", label: "Santa Lucía" },
  { value: "chimbas", label: "Chimbas" },
  { value: "pocito", label: "Pocito" },
  { value: "caucete", label: "Caucete" },
  { value: "25-de-mayo", label: "25 de Mayo" },
  { value: "ullum", label: "Ullum" },
  { value: "zonda", label: "Zonda" },
  { value: "sarmiento", label: "Sarmiento" },
  { value: "angaco", label: "Angaco" },
  { value: "albardon", label: "Albardón" },
  { value: "jachal", label: "Jáchal" },
  { value: "iglesia", label: "Iglesia" },
  { value: "calingasta", label: "Calingasta" },
  { value: "san-martin", label: "San Martín" },
  { value: "valle-fertil", label: "Valle Fértil" },
  { value: "otro", label: "Otro" },
];

export const CATEGORY_CONFIGS: CategoryConfig[] = [
  // ── 1. TECNOLOGÍA ─────────────────────────────────────────────
  {
    id: 1,
    name: "Tecnología",
    slug: "electronics",
    icon: "💻",
    subcats: [
      { value: "notebook", label: "Notebook / Laptop" },
      { value: "pc", label: "PC / Computadora de escritorio" },
      { value: "tablet", label: "Tablet" },
      { value: "monitor", label: "Monitor" },
      { value: "componentes-pc", label: "Componentes de PC" },
      { value: "impresion", label: "Impresión" },
      { value: "conectividad", label: "Conectividad y Redes" },
      { value: "tv", label: "Televisor" },
      { value: "audio", label: "Audio / Parlantes" },
      { value: "camara", label: "Cámara Digital / Filmadora" },
      { value: "acc-camara", label: "Accesorios para Cámaras" },
      { value: "consola", label: "Consola de Videojuegos" },
      { value: "videojuego", label: "Videojuego" },
      { value: "drone", label: "Drone" },
      { value: "acc-audio-video", label: "Electrónica / Audio y Video" },
      { value: "otro", label: "Otro" },
    ],
    fields: [
      {
        key: "sub_category",
        label: "Tipo de producto",
        type: "select",
        required: true,
        options: [
          { value: "notebook", label: "Notebook / Laptop" },
          { value: "pc", label: "PC / Computadora de escritorio" },
          { value: "tablet", label: "Tablet" },
          { value: "monitor", label: "Monitor" },
          { value: "componentes-pc", label: "Componentes de PC" },
          { value: "impresion", label: "Impresión" },
          { value: "conectividad", label: "Conectividad y Redes" },
          { value: "tv", label: "Televisor" },
          { value: "audio", label: "Audio / Parlantes" },
          { value: "camara", label: "Cámara Digital / Filmadora" },
          { value: "acc-camara", label: "Accesorios para Cámaras" },
          { value: "consola", label: "Consola de Videojuegos" },
          { value: "videojuego", label: "Videojuego" },
          { value: "drone", label: "Drone" },
          { value: "acc-audio-video", label: "Electrónica / Audio y Video" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "brand",
        label: "Marca",
        type: "text",
        placeholder: "Apple, Samsung, LG...",
      },
      {
        key: "model",
        label: "Modelo",
        type: "text",
        placeholder: "iPhone 14 Pro, Galaxy S23...",
      },
      {
        key: "storage",
        label: "Almacenamiento",
        type: "select",
        options: [
          { value: "16gb", label: "16 GB" },
          { value: "32gb", label: "32 GB" },
          { value: "64gb", label: "64 GB" },
          { value: "128gb", label: "128 GB" },
          { value: "256gb", label: "256 GB" },
          { value: "512gb", label: "512 GB" },
          { value: "1tb", label: "1 TB" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "ram",
        label: "RAM",
        type: "select",
        options: [
          { value: "2gb", label: "2 GB" },
          { value: "4gb", label: "4 GB" },
          { value: "6gb", label: "6 GB" },
          { value: "8gb", label: "8 GB" },
          { value: "12gb", label: "12 GB" },
          { value: "16gb", label: "16 GB" },
          { value: "32gb", label: "32 GB" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "color",
        label: "Color",
        type: "text",
        placeholder: "Negro, Blanco, Grafito...",
      },
      { key: "includes_box", label: "Incluye caja original", type: "checkbox" },
      { key: "includes_charger", label: "Incluye cargador", type: "checkbox" },
    ],
  },

  // ── 2. VEHÍCULOS ──────────────────────────────────────────────
  {
    id: 2,
    name: "Vehículos",
    slug: "vehicles",
    icon: "🚗",
    subcats: [
      { value: "auto", label: "Auto" },
      { value: "camioneta", label: "Pickup / SUV / Utilitario" },
      { value: "moto", label: "Moto" },
      { value: "cuatriciclo", label: "Cuatriciclo" },
      { value: "utv", label: "Areneros" },
      { value: "camion", label: "Camión" },
      { value: "nautica", label: "Náutica" },
      { value: "plan-ahorro", label: "Plan de Ahorro" },
      { value: "otro", label: "Otro" },
    ],
    fields: [
      {
        key: "sub_category",
        label: "Tipo de vehículo",
        type: "select",
        required: true,
        options: [
          { value: "auto", label: "Auto" },
          { value: "camioneta", label: "Pickup / SUV / Utilitario" },
          { value: "moto", label: "Moto" },
          { value: "cuatriciclo", label: "Cuatriciclo" },
          { value: "utv", label: "Areneros" },
          { value: "camion", label: "Camión" },
          { value: "nautica", label: "Náutica" },
          { value: "plan-ahorro", label: "Plan de Ahorro" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "brand",
        label: "Marca",
        type: "select",
        required: true,
        options: [
          { value: "toyota", label: "Toyota" },
          { value: "volkswagen", label: "Volkswagen" },
          { value: "ford", label: "Ford" },
          { value: "chevrolet", label: "Chevrolet" },
          { value: "renault", label: "Renault" },
          { value: "peugeot", label: "Peugeot" },
          { value: "fiat", label: "Fiat" },
          { value: "honda", label: "Honda" },
          { value: "hyundai", label: "Hyundai" },
          { value: "kia", label: "Kia" },
          { value: "nissan", label: "Nissan" },
          { value: "citroen", label: "Citroën" },
          { value: "bmw", label: "BMW" },
          { value: "mercedes-benz", label: "Mercedes-Benz" },
          { value: "audi", label: "Audi" },
          { value: "suzuki", label: "Suzuki" },
          { value: "jeep", label: "Jeep" },
          { value: "dodge", label: "Dodge" },
          { value: "chery", label: "Chery" },
          { value: "geely", label: "Geely" },
          { value: "byd", label: "BYD" },
          { value: "otra", label: "Otra marca" },
        ],
      },
      {
        key: "model",
        label: "Modelo",
        type: "text",
        placeholder: "Hilux, Gol, Corolla...",
        required: true,
      },
      {
        key: "year",
        label: "Año",
        type: "number",
        placeholder: "2020",
        required: true,
      },
      {
        key: "km",
        label: "Kilómetros",
        type: "number",
        placeholder: "50000",
        unit: "km",
        required: true,
      },
      {
        key: "fuel",
        label: "Combustible",
        type: "select",
        required: true,
        options: [
          { value: "nafta", label: "Nafta" },
          { value: "diesel", label: "Diesel" },
          { value: "gnc", label: "GNC" },
          { value: "glp", label: "GLP" },
          { value: "electrico", label: "Eléctrico" },
          { value: "hibrido", label: "Híbrido" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "transmission",
        label: "Transmisión",
        type: "select",
        options: [
          { value: "manual", label: "Manual" },
          { value: "automatica", label: "Automática" },
          { value: "cvt", label: "CVT" },
        ],
      },
      {
        key: "doors",
        label: "Puertas",
        type: "select",
        options: [
          { value: "2", label: "2 puertas" },
          { value: "3", label: "3 puertas" },
          { value: "4", label: "4 puertas" },
          { value: "5", label: "5 puertas" },
        ],
      },
      {
        key: "color",
        label: "Color",
        type: "text",
        placeholder: "Blanco, Negro, Rojo...",
      },
      {
        key: "first_owner",
        label: "Primera mano (único dueño)",
        type: "checkbox",
      },
      { key: "accepts_trade", label: "Acepta permuta", type: "checkbox" },
      {
        key: "seller_type",
        label: "Vendedor",
        type: "radio",
        options: [
          { value: "particular", label: "Particular" },
          { value: "concesionaria", label: "Concesionaria" },
        ],
      },
    ],
  },

  // ── 3. INMUEBLES ──────────────────────────────────────────────
  {
    id: 3,
    name: "Inmuebles",
    slug: "real-estate",
    icon: "🏠",
    subcats: [
      { value: "casa", label: "Casa" },
      { value: "departamento", label: "Departamento" },
      { value: "terreno", label: "Terreno / Lote" },
      { value: "finca", label: "Finca / Campo / Quinta" },
      { value: "local", label: "Local / Oficina / Consultorios" },
      { value: "galpon", label: "Galpón / Depósito" },
      { value: "cochera", label: "Cochera" },
      { value: "otro", label: "Otro" },
    ],
    fields: [
      {
        key: "sub_category",
        label: "Tipo de propiedad",
        type: "select",
        required: true,
        options: [
          { value: "casa", label: "Casa" },
          { value: "departamento", label: "Departamento" },
          { value: "terreno", label: "Terreno / Lote" },
          { value: "finca", label: "Finca / Campo / Quinta" },
          { value: "local", label: "Local / Oficina / Consultorios" },
          { value: "galpon", label: "Galpón / Depósito" },
          { value: "cochera", label: "Cochera" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "operation",
        label: "Operación",
        type: "radio",
        required: true,
        options: [
          { value: "venta", label: "Venta" },
          { value: "alquiler", label: "Alquiler" },
          { value: "alquiler-temporal", label: "Alquiler temporal" },
        ],
      },
      {
        key: "zone",
        label: "Departamento / Zona",
        type: "select",
        required: true,
        options: ZONAS_SJ,
      },
      {
        key: "bedrooms",
        label: "Dormitorios",
        type: "select",
        options: [
          { value: "monoambiente", label: "Monoambiente" },
          { value: "1", label: "1 dormitorio" },
          { value: "2", label: "2 dormitorios" },
          { value: "3", label: "3 dormitorios" },
          { value: "4", label: "4 dormitorios" },
          { value: "5+", label: "5 o más" },
        ],
      },
      {
        key: "bathrooms",
        label: "Baños",
        type: "select",
        options: [
          { value: "1", label: "1 baño" },
          { value: "2", label: "2 baños" },
          { value: "3", label: "3 baños" },
          { value: "4+", label: "4 o más" },
        ],
      },
      {
        key: "m2_covered",
        label: "Superficie cubierta",
        type: "number",
        placeholder: "80",
        unit: "m²",
      },
      {
        key: "m2_total",
        label: "Superficie total",
        type: "number",
        placeholder: "200",
        unit: "m²",
      },
      {
        key: "age",
        label: "Antigüedad",
        type: "select",
        options: [
          { value: "estrenar", label: "A estrenar" },
          { value: "0-5", label: "Menos de 5 años" },
          { value: "5-10", label: "5 a 10 años" },
          { value: "10-20", label: "10 a 20 años" },
          { value: "20-30", label: "20 a 30 años" },
          { value: "30+", label: "Más de 30 años" },
        ],
      },
      {
        key: "rooms",
        label: "Ambientes",
        type: "select",
        options: [
          { value: "1", label: "1 ambiente" },
          { value: "2", label: "2 ambientes" },
          { value: "3", label: "3 ambientes" },
          { value: "4", label: "4 ambientes" },
          { value: "5+", label: "5 o más" },
        ],
      },
      {
        key: "floor",
        label: "Piso (dpto)",
        type: "select",
        options: [
          { value: "pb", label: "Planta baja" },
          ...[1,2,3,4,5,6,7,8,9,10].map(f => ({ value: String(f), label: `${f}° piso` })),
          { value: "11+", label: "11° o superior" },
        ],
      },
      {
        key: "orientation",
        label: "Orientación",
        type: "select",
        options: [
          { value: "norte", label: "Norte" },
          { value: "sur", label: "Sur" },
          { value: "este", label: "Este" },
          { value: "oeste", label: "Oeste" },
          { value: "noreste", label: "Noreste" },
          { value: "noroeste", label: "Noroeste" },
          { value: "sureste", label: "Sureste" },
          { value: "suroeste", label: "Suroeste" },
        ],
      },
      {
        key: "heating",
        label: "Calefacción",
        type: "select",
        options: [
          { value: "central", label: "Central" },
          { value: "radiadores", label: "Radiadores" },
          { value: "split", label: "Split / A/A" },
          { value: "losa", label: "Losa radiante" },
          { value: "estufa", label: "Estufa" },
          { value: "ninguna", label: "Sin calefacción" },
        ],
      },
      { key: "garage", label: "Cochera incluida", type: "checkbox" },
      { key: "pool", label: "Pileta", type: "checkbox" },
      { key: "elevator", label: "Ascensor", type: "checkbox" },
      { key: "furnished", label: "Amoblado", type: "checkbox" },
      { key: "pets_allowed", label: "Mascotas permitidas", type: "checkbox" },
      { key: "air_conditioning", label: "Aire acondicionado", type: "checkbox" },
      { key: "laundry", label: "Lavadero", type: "checkbox" },
      { key: "storage", label: "Baulera", type: "checkbox" },
      { key: "grill", label: "Parrilla", type: "checkbox" },
      { key: "security", label: "Seguridad 24hs", type: "checkbox" },
      {
        key: "private_complex",
        label: "Barrio privado / Consorcio",
        type: "checkbox",
      },
      {
        key: "credit_eligible",
        label: "Apto crédito hipotecario",
        type: "checkbox",
      },
      {
        key: "seller_type",
        label: "Publicado por",
        type: "radio",
        options: [
          { value: "particular", label: "Dueño directo" },
          { value: "inmobiliaria", label: "Inmobiliaria" },
        ],
      },
      {
        key: "currency",
        label: "Moneda del precio",
        type: "radio",
        options: [
          { value: "ARS", label: "Pesos ($)" },
          { value: "USD", label: "Dólares (U$S)" },
        ],
      },
    ],
  },

  // ── 4. ROPA Y CALZADO ─────────────────────────────────────────
  {
    id: 4,
    name: "Ropa y Calzado",
    slug: "clothing",
    icon: "👗",
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "ropa", label: "Ropa" },
          { value: "calzado", label: "Calzado" },
          { value: "accesorio", label: "Accesorio" },
          { value: "bolso", label: "Bolso / Cartera" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "gender",
        label: "Género",
        type: "select",
        required: true,
        options: [
          { value: "mujer", label: "Mujer" },
          { value: "hombre", label: "Hombre" },
          { value: "unisex", label: "Unisex" },
          { value: "nino", label: "Niño/a" },
          { value: "bebe", label: "Bebé" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "size",
        label: "Talle",
        type: "text",
        placeholder: "S, M, L, XL, 42, 38...",
      },
      {
        key: "brand",
        label: "Marca",
        type: "text",
        placeholder: "Nike, Adidas, Zara...",
      },
      {
        key: "color",
        label: "Color",
        type: "text",
        placeholder: "Negro, Azul...",
      },
      {
        key: "material",
        label: "Material",
        type: "text",
        placeholder: "Algodón, Jean, Cuero...",
      },
    ],
  },

  // ── 5. HOGAR Y JARDÍN ─────────────────────────────────────────
  {
    id: 5,
    name: "Hogar y Muebles",
    slug: "home-garden",
    icon: "🛋️",
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "decoracion", label: "Decoración y Ambientación" },
          { value: "cocina-comedor", label: "Cocina y Comedor" },
          { value: "banos", label: "Baños y Sanitarios" },
          { value: "dormitorio", label: "Dormitorio y Descanso" },
          { value: "limpieza", label: "Limpieza del Hogar" },
          { value: "iluminacion", label: "Iluminación" },
          { value: "jardin-exterior", label: "Jardín y Exterior" },
          { value: "muebles", label: "Muebles y Estantes" },
          { value: "organizacion", label: "Organización y Almacenaje" },
          { value: "seguridad", label: "Seguridad del Hogar" },
          { value: "textil", label: "Textiles del Hogar" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "brand",
        label: "Marca",
        type: "text",
        placeholder: "Samsung, Whirlpool...",
      },
      {
        key: "color",
        label: "Color",
        type: "text",
        placeholder: "Blanco, Madera...",
      },
      {
        key: "material",
        label: "Material",
        type: "text",
        placeholder: "Madera, Metal, Tela...",
      },
      {
        key: "dimensions",
        label: "Medidas",
        type: "text",
        placeholder: "Alto x Ancho x Profundo",
      },
    ],
  },

  // ── 6. DEPORTES ───────────────────────────────────────────────
  {
    id: 6,
    name: "Deportes",
    slug: "sports",
    icon: "⚽",
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "futbol", label: "Fútbol" },
          { value: "bicicleta", label: "Bicicleta" },
          { value: "fitness", label: "Fitness / Gym" },
          { value: "pelota", label: "Pelotas / Equipos" },
          { value: "raqueta", label: "Raqueta / Pala" },
          { value: "natacion", label: "Natación" },
          { value: "camping", label: "Camping / Outdoor" },
          { value: "ropa-dep", label: "Ropa deportiva" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "brand",
        label: "Marca",
        type: "text",
        placeholder: "Nike, Adidas, Trek...",
      },
      {
        key: "size",
        label: "Talle / Rodado",
        type: "text",
        placeholder: 'M, 29", 42...',
      },
      {
        key: "color",
        label: "Color",
        type: "text",
        placeholder: "Negro, Rojo...",
      },
    ],
  },

  // ── 7. HERRAMIENTAS ───────────────────────────────────────────
  {
    id: 7,
    name: "Herramientas",
    slug: "tools",
    icon: "🔧",
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "accesorios", label: "Accesorios para Herramientas" },
          { value: "cajas-org",  label: "Cajas y Organizadores" },
          { value: "electrica",  label: "Herramientas Eléctricas" },
          { value: "industrial", label: "Herramientas Industriales" },
          { value: "manual",     label: "Herramientas Manuales" },
          { value: "neumatica",  label: "Herramientas Neumáticas" },
          { value: "jardineria", label: "Herramientas para Jardín" },
          { value: "medicion",   label: "Medición y Diagnóstico" },
          { value: "soldadura",  label: "Soldadura y Corte" },
          { value: "otro",       label: "Otro" },
        ],
      },
      {
        key: "brand",
        label: "Marca",
        type: "text",
        placeholder: "Bosch, DeWalt, Makita...",
      },
      {
        key: "voltage",
        label: "Voltaje",
        type: "select",
        options: [
          { value: "12v", label: "12V" },
          { value: "18v", label: "18V" },
          { value: "110v", label: "110V" },
          { value: "220v", label: "220V" },
          { value: "n/a", label: "N/A" },
        ],
      },
    ],
  },

  // ── 25. JUEGOS Y JUGUETES ──────────────────────────────────────
  {
    id: 25,
    name: "Juegos y Juguetes",
    slug: "toys",
    icon: "🧸",
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "juguetes-accion",   label: "Juguetes de Acción" },
          { value: "arte-manualidades", label: "Arte y Manualidades" },
          { value: "construccion",      label: "Construcción y Encastre" },
          { value: "juegos-mesa",       label: "Juegos de Mesa y Cartas" },
          { value: "juegos-exterior",   label: "Juegos al Aire Libre" },
          { value: "peluches",          label: "Peluches y Muñecos" },
          { value: "vehiculos-juguete", label: "Vehículos de Juguete" },
          { value: "juguetes-bebe",     label: "Juguetes para Bebés" },
          { value: "electronicos",      label: "Electrónicos para Niños" },
          { value: "puzzles",           label: "Puzzles y Rompecabezas" },
          { value: "patines",           label: "Patines y Monopatines" },
          { value: "instrumentos",      label: "Instrumentos Musicales Infantiles" },
          { value: "coleccionables",    label: "Figuritas y Coleccionables" },
          { value: "otro",              label: "Otro" },
        ],
      },
      {
        key: "brand",
        label: "Marca",
        type: "text",
        placeholder: "Lego, Hasbro, Mattel...",
      },
      {
        key: "age_range",
        label: "Edad recomendada",
        type: "select",
        options: [
          { value: "0-2",   label: "0 a 2 años" },
          { value: "3-5",   label: "3 a 5 años" },
          { value: "6-8",   label: "6 a 8 años" },
          { value: "9-12",  label: "9 a 12 años" },
          { value: "12+",   label: "12 años o más" },
        ],
      },
    ],
  },

  // ── 8. MÚSICA, LIBROS Y REVISTAS ──────────────────────────────
  {
    id: 8,
    name: "Música, Libros y Revistas",
    slug: "books",
    icon: "📚",
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "libros",     label: "Libros" },
          { value: "revistas",   label: "Revistas y Publicaciones" },
          { value: "comic-manga",label: "Cómics y Manga" },
          { value: "ebooks",     label: "Libros Digitales" },
          { value: "musica",     label: "Música (CDs y Vinilos)" },
          { value: "peliculas",  label: "Películas y Series" },
          { value: "cursos",     label: "Cursos y Tutoriales" },
          { value: "catalogos",  label: "Catálogos e Instructivos" },
          { value: "otro",       label: "Otro" },
        ],
      },
      {
        key: "author",
        label: "Autor / Artista / Editorial",
        type: "text",
        placeholder: "Stephen King, Beatles, Planeta...",
      },
      {
        key: "language",
        label: "Idioma",
        type: "select",
        options: [
          { value: "espanol", label: "Español" },
          { value: "ingles",  label: "Inglés" },
          { value: "otro",    label: "Otro" },
        ],
      },
    ],
  },

  // ── 9. MASCOTAS ───────────────────────────────────────────────
  {
    id: 9,
    name: "Mascotas",
    slug: "pets",
    icon: "🐾",
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "perros",        label: "Perros" },
          { value: "gatos",         label: "Gatos" },
          { value: "aves",          label: "Aves y Pájaros" },
          { value: "peces",         label: "Peces y Acuarios" },
          { value: "roedores",      label: "Roedores y Conejos" },
          { value: "reptiles",      label: "Reptiles y Anfibios" },
          { value: "caballos",      label: "Caballos y Equinos" },
          { value: "collar-correa", label: "Collares y Correas" },
          { value: "ropa-mascotas", label: "Ropa y Accesorios" },
          { value: "jaulas-camas",  label: "Jaulas, Camas y Transportes" },
          { value: "higiene",       label: "Higiene y Cuidado" },
          { value: "alimentacion",  label: "Alimentación y Snacks" },
          { value: "juguetes-mas",  label: "Juguetes para Mascotas" },
          { value: "otro",          label: "Otro" },
        ],
      },
      {
        key: "breed",
        label: "Raza",
        type: "text",
        placeholder: "Labrador, Persa, Criolla...",
      },
      {
        key: "age",
        label: "Edad",
        type: "text",
        placeholder: "2 años, 3 meses...",
      },
      {
        key: "sex",
        label: "Sexo",
        type: "radio",
        options: [
          { value: "macho", label: "Macho" },
          { value: "hembra", label: "Hembra" },
        ],
      },
      { key: "vaccinated", label: "Vacunado", type: "checkbox" },
      { key: "pedigree", label: "Con pedigree", type: "checkbox" },
      {
        key: "is_adoption",
        label: "Es adopción (gratis)",
        type: "checkbox",
        hint: "Marcá si el animal se da en adopción gratuitamente",
      },
    ],
  },

  // ── 26. SERVICIOS ─────────────────────────────────────────────
  {
    id: 26,
    name: "Servicios",
    slug: "services",
    icon: "🛠️",
    fields: [
      {
        key: "sub_category",
        label: "Rubro",
        type: "select",
        required: true,
        options: [
          { value: "asesoramiento",  label: "Asesoramiento Legal y Contable" },
          { value: "belleza-serv",   label: "Belleza y Estética" },
          { value: "diseno",         label: "Diseño y Comunicación" },
          { value: "cursos",         label: "Cursos y Clases" },
          { value: "delivery",       label: "Delivery y Envíos" },
          { value: "eventos",        label: "Fiestas y Eventos" },
          { value: "fotografia",     label: "Fotografía y Audiovisual" },
          { value: "construccion",   label: "Construcción y Reformas" },
          { value: "imprenta",       label: "Imprenta y Gráfica" },
          { value: "mecanica",       label: "Mecánica y Vehículos" },
          { value: "salud",          label: "Salud y Bienestar" },
          { value: "mascotas-serv",  label: "Servicios para Mascotas" },
          { value: "limpieza",       label: "Limpieza y Mantenimiento" },
          { value: "informatica",    label: "Informática y Tecnología" },
          { value: "transporte",     label: "Transporte y Mudanzas" },
          { value: "turismo",        label: "Turismo y Viajes" },
          { value: "otro",           label: "Otro" },
        ],
      },
      {
        key: "modality",
        label: "Modalidad",
        type: "select",
        options: [
          { value: "presencial",  label: "Presencial" },
          { value: "online",      label: "Online / Remoto" },
          { value: "ambas",       label: "Presencial y Online" },
        ],
      },
      {
        key: "brand",
        label: "Empresa / Profesional",
        type: "text",
        placeholder: "Nombre del negocio o profesional...",
      },
    ],
  },

  // ── 10. OTROS ─────────────────────────────────────────────────
  {
    id: 10,
    name: "Otros",
    slug: "other",
    icon: "📦",
    subcats: [
      { value: "arte-antiguedades",  label: "Arte y Antigüedades" },
      { value: "coleccionables",     label: "Coleccionables" },
      { value: "instrumentos",       label: "Instrumentos Musicales" },
      { value: "joyeria-relojes",    label: "Joyería y Relojes" },
      { value: "videojuegos",        label: "Videojuegos y Consolas" },
      { value: "industria-comercio", label: "Industria y Comercio" },
      { value: "oficina-libreria",   label: "Oficina y Librería" },
      { value: "alimentos-bebidas",  label: "Alimentos y Bebidas" },
      { value: "construccion",       label: "Materiales de Construcción" },
      { value: "campo-agro",         label: "Campo y Agro" },
      { value: "souvenirs-fiestas",  label: "Souvenirs y Fiestas" },
      { value: "viajes-turismo",     label: "Viajes y Turismo" },
      { value: "otro",               label: "Otro" },
    ],
    fields: [
      {
        key: "sub_category",
        label: "Subcategoría",
        type: "select",
        required: true,
        options: [
          { value: "arte-antiguedades",  label: "Arte y Antigüedades" },
          { value: "coleccionables",     label: "Coleccionables" },
          { value: "instrumentos",       label: "Instrumentos Musicales" },
          { value: "joyeria-relojes",    label: "Joyería y Relojes" },
          { value: "videojuegos",        label: "Videojuegos y Consolas" },
          { value: "industria-comercio", label: "Industria y Comercio" },
          { value: "oficina-libreria",   label: "Oficina y Librería" },
          { value: "alimentos-bebidas",  label: "Alimentos y Bebidas" },
          { value: "construccion",       label: "Materiales de Construcción" },
          { value: "campo-agro",         label: "Campo y Agro" },
          { value: "souvenirs-fiestas",  label: "Souvenirs y Fiestas" },
          { value: "viajes-turismo",     label: "Viajes y Turismo" },
          { value: "otro",               label: "Otro" },
        ],
      },
      { key: "brand", label: "Marca / Fabricante", type: "text", placeholder: "Opcional" },
    ],
  },

  // ── 11. CELULARES ─────────────────────────────────────────────
  {
    id: 21,
    name: "Celulares",
    slug: "phones",
    icon: "📱",
    subcats: [
      { value: "smartphone", label: "Celulares y Smartphones" },
      { value: "basico", label: "Teléfonos básicos" },
      { value: "accesorio", label: "Accesorios para Celulares" },
      { value: "repuesto", label: "Repuestos y Partes" },
      { value: "otro", label: "Otro" },
    ],
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "smartphone", label: "Celulares y Smartphones" },
          { value: "basico", label: "Teléfonos básicos" },
          { value: "accesorio", label: "Accesorios para Celulares" },
          { value: "repuesto", label: "Repuestos y Partes" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "brand",
        label: "Marca",
        type: "select",
        required: true,
        options: [
          { value: "apple", label: "Apple" },
          { value: "samsung", label: "Samsung" },
          { value: "motorola", label: "Motorola" },
          { value: "xiaomi", label: "Xiaomi" },
          { value: "lg", label: "LG" },
          { value: "huawei", label: "Huawei" },
          { value: "nokia", label: "Nokia" },
          { value: "oppo", label: "OPPO" },
          { value: "realme", label: "Realme" },
          { value: "tcl", label: "TCL" },
          { value: "alcatel", label: "Alcatel" },
          { value: "zte", label: "ZTE" },
          { value: "google", label: "Google" },
          { value: "oneplus", label: "OnePlus" },
          { value: "otra", label: "Otra marca" },
        ],
      },
      { key: "model", label: "Modelo", type: "text", placeholder: "iPhone 15, Galaxy A54, Moto G84..." },
      {
        key: "storage",
        label: "Almacenamiento interno",
        type: "select",
        options: [
          { value: "16gb", label: "16 GB" },
          { value: "32gb", label: "32 GB" },
          { value: "64gb", label: "64 GB" },
          { value: "128gb", label: "128 GB" },
          { value: "256gb", label: "256 GB" },
          { value: "512gb", label: "512 GB" },
          { value: "1tb", label: "1 TB" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "ram",
        label: "Memoria RAM",
        type: "select",
        options: [
          { value: "2gb", label: "2 GB" },
          { value: "3gb", label: "3 GB" },
          { value: "4gb", label: "4 GB" },
          { value: "6gb", label: "6 GB" },
          { value: "8gb", label: "8 GB" },
          { value: "12gb", label: "12 GB" },
          { value: "16gb", label: "16 GB" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "os",
        label: "Sistema operativo",
        type: "select",
        options: [
          { value: "android", label: "Android" },
          { value: "ios", label: "iOS (iPhone)" },
          { value: "harmonyos", label: "HarmonyOS" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "sim_type",
        label: "Tipo de SIM",
        type: "select",
        options: [
          { value: "nano-sim", label: "Nano SIM" },
          { value: "dual-sim", label: "Dual SIM" },
          { value: "esim", label: "eSIM" },
          { value: "dual-sim-esim", label: "Dual SIM + eSIM" },
          { value: "micro-sim", label: "Micro SIM" },
        ],
      },
      { key: "color", label: "Color", type: "text", placeholder: "Negro, Blanco, Azul medianoche..." },
      { key: "includes_box", label: "Incluye caja original", type: "checkbox" },
      { key: "includes_charger", label: "Incluye cargador", type: "checkbox" },
      { key: "unlocked", label: "Liberado (libre de operadora)", type: "checkbox" },
      { key: "accepts_trade", label: "Acepta permuta", type: "checkbox" },
    ],
  },

  // ── 12. ELECTRODOMÉSTICOS ─────────────────────────────────────
  {
    id: 22,
    name: "Electrodomésticos",
    slug: "appliances",
    icon: "🧊",
    subcats: [
      { value: "heladera", label: "Heladera / Freezer" },
      { value: "lavarropas", label: "Lavarropas / Secarropas" },
      { value: "cocina", label: "Cocina / Horno" },
      { value: "microondas", label: "Microondas" },
      { value: "aire", label: "Aire acondicionado / Calefactor" },
      { value: "aspiradora", label: "Aspiradora / Limpieza" },
      { value: "pequeno", label: "Pequeño electrodoméstico" },
      { value: "otro", label: "Otro" },
    ],
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "heladera", label: "Heladera / Freezer" },
          { value: "lavarropas", label: "Lavarropas / Secarropas" },
          { value: "cocina", label: "Cocina / Horno" },
          { value: "microondas", label: "Microondas" },
          { value: "aire", label: "Aire acondicionado / Calefactor" },
          { value: "aspiradora", label: "Aspiradora / Limpieza" },
          { value: "pequeno", label: "Pequeño electrodoméstico" },
          { value: "otro", label: "Otro" },
        ],
      },
      {
        key: "brand",
        label: "Marca",
        type: "select",
        options: [
          { value: "samsung", label: "Samsung" },
          { value: "lg", label: "LG" },
          { value: "whirlpool", label: "Whirlpool" },
          { value: "mabe", label: "Mabe" },
          { value: "drean", label: "Drean" },
          { value: "ariston", label: "Ariston" },
          { value: "electrolux", label: "Electrolux" },
          { value: "bosch", label: "Bosch" },
          { value: "philips", label: "Philips" },
          { value: "oster", label: "Oster" },
          { value: "moulinex", label: "Moulinex" },
          { value: "rowenta", label: "Rowenta" },
          { value: "hitachi", label: "Hitachi" },
          { value: "midea", label: "Midea" },
          { value: "carrier", label: "Carrier" },
          { value: "tcl", label: "TCL" },
          { value: "otra", label: "Otra marca" },
        ],
      },
      { key: "model", label: "Modelo", type: "text", placeholder: "Opcional" },
      {
        key: "capacity",
        label: "Capacidad",
        type: "text",
        placeholder: "300 litros, 7 kg, 2400 W...",
        hint: "Litros para heladeras, kg para lavarropas, BTU para aire acondicionado",
      },
      {
        key: "voltage",
        label: "Voltaje",
        type: "select",
        options: [
          { value: "220v", label: "220V" },
          { value: "110v", label: "110V" },
          { value: "dual", label: "Dual (110V / 220V)" },
        ],
      },
      {
        key: "energy_efficiency",
        label: "Eficiencia energética",
        type: "select",
        options: [
          { value: "a+++", label: "A+++" },
          { value: "a++", label: "A++" },
          { value: "a+", label: "A+" },
          { value: "a", label: "A" },
          { value: "b", label: "B" },
          { value: "c", label: "C" },
          { value: "no-aplica", label: "No especificada" },
        ],
      },
      {
        key: "warranty",
        label: "Garantía",
        type: "select",
        options: [
          { value: "sin-garantia", label: "Sin garantía" },
          { value: "3m", label: "3 meses" },
          { value: "6m", label: "6 meses" },
          { value: "1a", label: "1 año" },
          { value: "2a", label: "2 años" },
          { value: "3a+", label: "3 años o más" },
        ],
      },
      {
        key: "color",
        label: "Color / Acabado",
        type: "select",
        options: [
          { value: "blanco", label: "Blanco" },
          { value: "gris", label: "Gris / Plata" },
          { value: "negro", label: "Negro" },
          { value: "acero", label: "Acero inoxidable" },
          { value: "otro", label: "Otro" },
        ],
      },
      { key: "accepts_trade", label: "Acepta permuta", type: "checkbox" },
    ],
  },

  // ── 13. BEBÉS Y NIÑOS ─────────────────────────────────────────
  {
    id: 23,
    name: "Bebés y Niños",
    slug: "babies",
    icon: "👶",
    subcats: [
      { value: "andadores",    label: "Andadores y Vehículos" },
      { value: "bano",         label: "Artículos de Baño" },
      { value: "maternidad",   label: "Maternidad y Embarazo" },
      { value: "chupetes",     label: "Chupetes y Mordillos" },
      { value: "alimentacion", label: "Comida y Alimentación" },
      { value: "corralito",    label: "Corralitos y Cunas" },
      { value: "cuarto",       label: "Cuarto del Bebé" },
      { value: "higiene",      label: "Higiene y Cuidado" },
      { value: "juguetes-bebe","label": "Juguetes para Bebés" },
      { value: "lactancia",    label: "Lactancia" },
      { value: "paseo",        label: "Paseo y Transporte" },
      { value: "ropa",         label: "Ropa y Calzado" },
      { value: "salud",        label: "Salud del Bebé" },
      { value: "seguridad",    label: "Seguridad para Bebés" },
      { value: "otro",         label: "Otro" },
    ],
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "andadores",    label: "Andadores y Vehículos" },
          { value: "bano",         label: "Artículos de Baño" },
          { value: "maternidad",   label: "Maternidad y Embarazo" },
          { value: "chupetes",     label: "Chupetes y Mordillos" },
          { value: "alimentacion", label: "Comida y Alimentación" },
          { value: "corralito",    label: "Corralitos y Cunas" },
          { value: "cuarto",       label: "Cuarto del Bebé" },
          { value: "higiene",      label: "Higiene y Cuidado" },
          { value: "juguetes-bebe",label: "Juguetes para Bebés" },
          { value: "lactancia",    label: "Lactancia" },
          { value: "paseo",        label: "Paseo y Transporte" },
          { value: "ropa",         label: "Ropa y Calzado" },
          { value: "salud",        label: "Salud del Bebé" },
          { value: "seguridad",    label: "Seguridad para Bebés" },
          { value: "otro",         label: "Otro" },
        ],
      },
      {
        key: "age_range",
        label: "Edad recomendada",
        type: "select",
        options: [
          { value: "0-3m", label: "0 a 3 meses" },
          { value: "3-6m", label: "3 a 6 meses" },
          { value: "6-12m", label: "6 a 12 meses" },
          { value: "1-2y", label: "1 a 2 años" },
          { value: "2-4y", label: "2 a 4 años" },
          { value: "4-6y", label: "4 a 6 años" },
          { value: "6-8y", label: "6 a 8 años" },
          { value: "8-12y", label: "8 a 12 años" },
          { value: "12+y", label: "12 años o más" },
        ],
      },
      {
        key: "size",
        label: "Talle",
        type: "text",
        placeholder: "RN, 0-3M, 3-6M, 1, 2, 4, 6, 8, 10...",
        hint: "Para ropa: RN=recién nacido, luego meses o años",
      },
      { key: "brand", label: "Marca", type: "text", placeholder: "Chicco, Graco, Fisher-Price, Lego..." },
      {
        key: "gender",
        label: "Género",
        type: "select",
        options: [
          { value: "nino", label: "Niño" },
          { value: "nina", label: "Niña" },
          { value: "unisex", label: "Unisex" },
        ],
      },
      { key: "color", label: "Color", type: "text", placeholder: "Azul, Rosa, Multicolor..." },
      {
        key: "material",
        label: "Material",
        type: "text",
        placeholder: "Algodón, Plástico, Madera...",
        hint: "Importante para ropa y juguetes",
      },
      { key: "includes_manual", label: "Incluye manual / instrucciones", type: "checkbox" },
    ],
  },

  // ── 14. BELLEZA Y SALUD ───────────────────────────────────────
  {
    id: 24,
    name: "Belleza y Salud",
    slug: "beauty-health",
    icon: "💄",
    subcats: [
      { value: "cuidado-personal", label: "Cuidado personal" },
      { value: "maquillaje", label: "Maquillaje" },
      { value: "perfume", label: "Perfume / Fragancia" },
      { value: "capilar", label: "Cuidado capilar" },
      { value: "equipo-medico", label: "Equipo médico" },
      { value: "suplemento", label: "Suplemento / Vitaminas" },
      { value: "optica", label: "Óptica / Anteojos" },
      { value: "otro", label: "Otro" },
    ],
    fields: [
      {
        key: "sub_category",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "cuidado-personal", label: "Cuidado personal" },
          { value: "maquillaje", label: "Maquillaje" },
          { value: "perfume", label: "Perfume / Fragancia" },
          { value: "capilar", label: "Cuidado capilar" },
          { value: "equipo-medico", label: "Equipo médico" },
          { value: "suplemento", label: "Suplemento / Vitaminas" },
          { value: "optica", label: "Óptica / Anteojos" },
          { value: "otro", label: "Otro" },
        ],
      },
      { key: "brand", label: "Marca", type: "text", placeholder: "L'Oréal, Nivea, Maybelline, Philips..." },
      { key: "volume", label: "Volumen / Cantidad", type: "text", placeholder: "100ml, 50g, 30 cápsulas..." },
      {
        key: "target",
        label: "Para",
        type: "select",
        options: [
          { value: "mujer", label: "Mujer" },
          { value: "hombre", label: "Hombre" },
          { value: "unisex", label: "Unisex" },
          { value: "nino", label: "Niño/a" },
        ],
      },
      {
        key: "skin_type",
        label: "Tipo de piel / cabello",
        type: "select",
        options: [
          { value: "seco", label: "Seco" },
          { value: "graso", label: "Graso" },
          { value: "mixto", label: "Mixto" },
          { value: "normal", label: "Normal" },
          { value: "sensible", label: "Sensible" },
          { value: "danado", label: "Dañado / Teñido" },
          { value: "rizado", label: "Rizado" },
          { value: "todos", label: "Todos los tipos" },
          { value: "no-aplica", label: "No aplica" },
        ],
      },
      {
        key: "fragrance_type",
        label: "Tipo de fragancia",
        type: "select",
        hint: "Solo para perfumes",
        options: [
          { value: "edp", label: "Eau de Parfum (EDP)" },
          { value: "edt", label: "Eau de Toilette (EDT)" },
          { value: "edc", label: "Eau de Cologne (EDC)" },
          { value: "parfum", label: "Parfum / Extrait" },
          { value: "no-aplica", label: "No aplica" },
        ],
      },
      { key: "is_original", label: "Producto original (no réplica)", type: "checkbox" },
      { key: "is_sealed", label: "Sellado / Sin uso", type: "checkbox" },
    ],
  },
];

// Helper: get config by category_id
export function getCategoryConfig(
  categoryId: number,
): CategoryConfig | undefined {
  return CATEGORY_CONFIGS.find((c) => c.id === categoryId);
}

// Helper: get config by slug
export function getCategoryBySlug(slug: string): CategoryConfig | undefined {
  return CATEGORY_CONFIGS.find((c) => c.slug === slug);
}
